services:
  vintagestory:
    build: .
    image: vintagestory:1.22.5
    container_name: vs-server
    restart: unless-stopped
    stdin_open: true # -i
    tty: true # -t
    ports:
      - "42420:42420/udp"
      - "42420:42420/tcp"
    volumes:
      - ./data:/data
